Candidate: CVE-2017-18342
PublicDate: 2018-06-27 12:29:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18342
 https://github.com/yaml/pyyaml/pull/74
Description:
 In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if
 used with untrusted data. The load() function has been deprecated in
 version 5.1 and the 'UnsafeLoader' has been introduced for backward
 compatibility with the function.
Ubuntu-Description:
Notes:
 seth-arnold> The patch changes the incredibly-unsafe yaml.load to the
  behaviour of safe_load; despite being many years overdue, it's also
  likely to break something.
 mdeslaur> upstream has reverted the 4.1 fix, so as of 2020-10-06, there
 mdeslaur> is no proper fix for this issue for stable releases, and fixing
 mdeslaur> it is likely to cause compatibility issues. In stable releases
 mdeslaur> individual software would need to be fixed instead of pyyaml
 mdeslaur> itself. We are not going to be fixing pyyaml itself, marking as
 mdeslaur> ignored.
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902878
Priority: low
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H [9.8 CRITICAL]
 nvd: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H [9.8 CRITICAL]


Patches_pyyaml:
upstream_pyyaml: needed
precise/esm_pyyaml: ignored
trusty_pyyaml: ignored (reached end-of-life)
trusty/esm_pyyaml: ignored
xenial_pyyaml: ignored
esm-infra/xenial_pyyaml: ignored
bionic_pyyaml: ignored
cosmic_pyyaml: ignored (reached end-of-life)
disco_pyyaml: ignored (reached end-of-life)
eoan_pyyaml: not-affected (5.1.2-1)
focal_pyyaml: not-affected (5.1.2-1)
devel_pyyaml: not-affected (5.1.2-1)
