Candidate: CVE-2023-23931
PublicDate: 2023-02-07 21:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23931
 https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r
 https://github.com/pyca/cryptography/commit/9fbf84efc861668755ab645530ec7be9cf3c6696
 https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3
Description:
 cryptography is a package designed to expose cryptographic primitives and
 recipes to Python developers. In affected versions `Cipher.update_into`
 would accept Python objects which implement the buffer protocol, but
 provide only immutable buffers. This would allow immutable objects (such as
 `bytes`) to be mutated, thus violating fundamental rules of Python and
 resulting in corrupted output. This now correctly raises an exception. This
 issue has been present since `update_into` was originally introduced in
 cryptography 1.8.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031049
Priority: medium
Discovered-by:
Assigned-to:
CVSS:

Patches_python-cryptography:
upstream_python-cryptography: needs-triage
esm-infra/xenial_python-cryptography: needs-triage
trusty_python-cryptography: ignored (out of standard support)
xenial_python-cryptography: ignored (out of standard support)
bionic_python-cryptography: needs-triage
focal_python-cryptography: needs-triage
jammy_python-cryptography: needs-triage
kinetic_python-cryptography: needs-triage
devel_python-cryptography: needs-triage
