Candidate: CVE-2023-23931
PublicDate: 2023-02-07 21:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23931
 https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r
 https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3
Description:
 cryptography is a package designed to expose cryptographic primitives and
 recipes to Python developers. In affected versions `Cipher.update_into`
 would accept Python objects which implement the buffer protocol, but
 provide only immutable buffers. This would allow immutable objects (such as
 `bytes`) to be mutated, thus violating fundamental rules of Python and
 resulting in corrupted output. This now correctly raises an exception. This
 issue has been present since `update_into` was originally introduced in
 cryptography 1.8.
Ubuntu-Description:
Notes:
 mdeslaur> Per the upstream advisory: "This is a soundness bug -- it allows
 mdeslaur> programmers to misuse an API, it cannot be exploited by attacker
 mdeslaur> controlled data alone."
 seth-arnold> Debian's update was incomplete, see 2.6.1-3+deb10u4
Mitigation:
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031049
Priority: low
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L [6.5 MEDIUM]

Patches_python-cryptography:
 upstream: https://github.com/pyca/cryptography/commit/9fbf84efc861668755ab645530ec7be9cf3c6696
upstream_python-cryptography: released (39.0.1)
esm-infra/xenial_python-cryptography: needed
trusty_python-cryptography: ignored (out of standard support)
xenial_python-cryptography: ignored (out of standard support)
bionic_python-cryptography: needed
focal_python-cryptography: needed
jammy_python-cryptography: needed
kinetic_python-cryptography: needed
devel_python-cryptography: needed
