Candidate: CVE-2023-41164
PublicDate: 2023-09-04 11:00:00 UTC
CRD: 2023-09-04 11:00:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-41164
 https://marc.info/?l=oss-security&m=169382648621342
Description:
 [Potential denial of service vulnerability in
 django.utils.encoding.uri_to_iri()]
Ubuntu-Description:
Notes:
 alexmurray> According to the upstream advisory affects versions 3.2.x,
  4.1.x and 4.2.x with fixes in 3.2.21, 4.1.11 and 4.2.5 respectively
Mitigation:
Bugs:
Priority: medium
Discovered-by: MProgrammer
Assigned-to:
CVSS:

Patches_python-django:
 upstream: https://github.com/django/django/commit/3f41d6d62929dfe53eda8109b3b836f26645bdce (main)
 upstream: https://github.com/django/django/commit/9c51b4dcfa0cefcb48231f4d71cafa80821f87b9 (4.2)
 upstream: https://github.com/django/django/commit/ba00bc5ec6a7eff5e08be438f7b5b0e9574e8ff0 (4.1)
 upstream: https://github.com/django/django/commit/6f030b1149bd8fa4ba90452e77cb3edc095ce54e (3.2)
upstream_python-django: needs-triage
trusty_python-django: ignored (end of standard support)
trusty/esm_python-django: needs-triage
xenial_python-django: ignored (end of standard support)
esm-infra/xenial_python-django: needed
bionic_python-django: ignored (end of standard support)
esm-infra/bionic_python-django: needed
focal_python-django: needed
jammy_python-django: needed
lunar_python-django: needed
devel_python-django: needed
