Candidate: CVE-2022-22846
PublicDate: 2022-01-10 14:12:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-22846
Description:
 The dnslib package through 0.9.16 for Python does not verify that the ID
 value in a DNS reply matches an ID value in a query.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 https://github.com/paulc/dnslib/issues/30
Priority: low
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N [5.3 MEDIUM]


Patches_python-dnslib:
 upstream: https://github.com/paulc/dnslib/commit/76e8677699ed098387d502c57980f58da642aeba
upstream_python-dnslib: needs-triage
trusty_python-dnslib: ignored (out of standard support)
xenial_python-dnslib: ignored (out of standard support)
bionic_python-dnslib: needs-triage
focal_python-dnslib: needs-triage
hirsute_python-dnslib: ignored (reached end-of-life)
impish_python-dnslib: ignored (reached end-of-life)
jammy_python-dnslib: needs-triage
devel_python-dnslib: needs-triage
